import Head from "next/head";
import Auth from "../../components/Auth";
import { AuthRedirect } from "../../hooks/authUser";

export default function Home() {
  AuthRedirect();

  return (
    <div /*className={styles.container}*/>
      <Head>
        <title>IziQ-Study</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Auth />
    </div>
  );
}
